# Generated by Django 5.2 on 2025-04-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='User email'),
        ),
    ]
