# Generated by Django 5.2 on 2025-04-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_emailotp_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
