# Generated by Django 5.2 on 2025-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_emailotp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
